### ISSUE TITLE
Add Docs Stub For GitHub and Heroku User Management

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/github-docs#27]
People mentioned other people needing documentation on how to manage users on GitHub and Heroku. When I have to do tasks related to user management, I just look at the GH and Heroku docs on the subject.

There is already a stub for GH management in `github-docs` and also a Heroku section.

- https://github.com/enterprise

I thought it would be easy to find the GitHub docs, but now this is Enterprise scope, I think user management changes. That is the enterprise website and the docs I quickly saw had "Enterprise Server Edition" on them...no idea at this point.

The Heroku docs are easier to locate, and I think the DE account will remain the same so the process should be as it is now.

- https://devcenter.heroku.com/articles/org-users-access
- https://www.heroku.com/enterprise

**Comment by alexfinnarn** [comment]
@mattroush Is work like this something to gather together for that larger group or wait until there's more information?

**Comment by mattroush** [comment]
@alexfinnarn gather, yes - we will want to share at some point. I think that point will come in the next couple of weeks, but if we share now without a deliberate next step, it'll just get lost in the wild and we'll end up re-sharing later anyway.

**Comment by alexfinnarn** [comment]
I also added a note at https://github.com/CUCentralAdvancement/heroku-docs#user-management
